server:
  bind_ip   : "0.0.0.0"
  bind_port : 5001
  debug     : True

database:
  dbname    : "testingstuff"
  dialect   : "postgresql"
  driver    : null
  host      : null
  password  : "a"
  port      : null
  username  : "fakeuser"
