server:
  bind_ip   : "0.0.0.0"
  bind_port : 5001
  debug     : True

database:
  dbname    : "pastedb"
  dialect   : "postgresql
  driver    : null
  host      : null
  password  : null
  port      : null
  username  : null
